-- require("plugins.nvim-lspconfig")
require("plugins.catppuccin")
require("plugins.mason")
-- require("plugins.mason-lspconfig")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.nvim-web-devicons")
require("plugins.lualine")
require("plugins.telescope")
