require("plugins.catppuccin")
require("plugins.lsp_config")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.nvim-web-devicons")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.harpoon")
require("plugins.blank-line")
-- require("plugins.plenary")
